export const LOAD_ACCOMPANIMENT_SUCCESS = 'LOAD_ACCOMPANIMENT_SUCCESS';
export const LOAD_DISHES_SUCCESS = 'LOAD_DISHES_SUCCESS';

export const ADD_ORDER = 'ADD_ORDER';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
