export const LOAD_ACCOMPANIMENT_SUCCESS = 'LOAD_ACCOMPANIMENT_SUCCESS';
export const LOAD_DISHES_SUCCESS = 'LOAD_DISHES_SUCCESS';

export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_MISSING = 'LOAD_PROFILE_MISSING';

export const LOAD_DELIVERIES_SUCCESS = 'LOAD_DELIVERIES_SUCCESS';

export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
