// Dishes
export const LOAD_DISHES_SUCCESS = 'LOAD_DISHES_SUCCESS'
export const LOAD_SIDE_DISHES_SUCCESS = 'LOAD_SIDE_DISHES_SUCCESS'

// Categories
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'

// Locations
export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS'
export const LOAD_AREAS_SUCCESS = 'LOAD_AREAS_SUCCESS'
export const SUBMIT_LOCATION = 'SUBMIT_LOCATION'

// Notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

// Deliveries
export const LOAD_DELIVERIES_SUCCESS = 'LOAD_DELIVERIES_SUCCESS'


// Session
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'


// Profile
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'


// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
